<a href="https://colab.research.google.com/github/JoseAlberto88/PyTorch_ML_Portfolio/blob/main/notebooks/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello I'm exited to learn PyTorch!")

## 00. PyTorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


# Introduction to Tensors
### Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([4, 4])
vector

tensor([4, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 1, 1],
                        [2, 2, 2],
                        [2, 3, 3]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 1, 1],
                        [2, 2, 2],
                        [2, 3, 3]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 1, 1],
         [2, 2, 2],
         [2, 3, 3]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 1, 1],
         [2, 2, 2],
         [2, 3, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([4, 3, 3])

In [ ]:
TENSOR[0], TENSOR[1], TENSOR[2], TENSOR[3]

(tensor([[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [2, 3, 3]]),
 tensor([[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]),
 tensor([[1, 1, 1],
         [2, 2, 2],
         [2, 3, 3]]))

In [ ]:
TENSOR[0].shape, TENSOR[0][1], TENSOR[0][2]

(torch.Size([3, 3]), tensor([3, 6, 9]), tensor([2, 4, 5]))

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update randomm numbers'

Torch random tensors https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3759, 0.6593, 0.9866, 0.8342],
        [0.1950, 0.6007, 0.2597, 0.8261],
        [0.5346, 0.3414, 0.3701, 0.1359]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[5.8086e-01, 8.3912e-02, 3.4569e-01,  ..., 4.7781e-01,
          6.8392e-01, 3.9104e-01],
         [1.5768e-01, 2.5911e-01, 8.1461e-02,  ..., 8.8363e-01,
          7.2128e-01, 4.1170e-01],
         [1.9980e-01, 5.0536e-02, 8.9079e-01,  ..., 2.1589e-01,
          3.0732e-01, 7.2204e-01],
         ...,
         [9.3859e-01, 3.3080e-01, 3.3611e-01,  ..., 2.0346e-01,
          4.4816e-02, 9.7930e-01],
         [7.2795e-01, 4.7844e-01, 7.7483e-01,  ..., 3.6943e-01,
          5.5756e-02, 3.6610e-01],
         [3.6842e-04, 7.4007e-01, 1.1075e-01,  ..., 9.9533e-01,
          1.4117e-01, 4.0074e-01]],

        [[2.8139e-01, 6.2045e-01, 7.3797e-01,  ..., 5.3021e-01,
          8.1182e-01, 1.4884e-01],
         [4.2931e-01, 4.2054e-01, 1.1356e-01,  ..., 9.0484e-01,
          7.9606e-02, 4.5995e-01],
         [4.6089e-02, 4.0840e-01, 9.0233e-01,  ..., 1.9436e-01,
          4.8752e-01, 8.2382e-01],
         ...,
         [1.8411e-01, 2.3056e-01, 4.3330e-01,  ..., 1.8895e-01,
          3.274

In [ ]:
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0,10)

/tmp/ipykernel_5364/3858421243.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors-like
ten_zerous = torch.zeros_like(input=one_to_ten)
ten_zerous

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors with PyTorch & Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3, 6, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype


torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatypes - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape froma tensor, can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor, can use 'tensor.device'

In [ ]:
# Create a tensor
some_tensor = torch.rand((3,4))
some_tensor

tensor([[0.2847, 0.6213, 0.5870, 0.7648],
        [0.0216, 0.7995, 0.5544, 0.8539],
        [0.3601, 0.8880, 0.5267, 0.9540]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2847, 0.6213, 0.5870, 0.7648],
        [0.0216, 0.7995, 0.5544, 0.8539],
        [0.3601, 0.8880, 0.5267, 0.9540]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 100 to it
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor-10

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of perfoming multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work

2. The resulting matrix has the shape of the **outer dimensions**
* '(2,3) @ (3,2) -> (2,2)'
* '(3,2) @ (2,3) -> (3,3)'

In [ ]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.37 ms, sys: 65 µs, total: 1.43 ms
Wall time: 3.12 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 88 µs, sys: 16 µs, total: 104 µs
Wall time: 72.5 µs


tensor(14)

### One of the common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_B.T,tensor_A)

tensor([[ 76, 100],
        [103, 136]])

Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Creating a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean -note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [ ]:
# Find teh position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor  that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors.

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an  extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(9,1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[0] = 5
z, x

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with un squeeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shift axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channel, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with Python is similar to indexing with Numpy.

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

## Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> torch.from_numpy (ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...

To reduce the randomness in neural networks and Pytorch comes the concept of **random seed.**

Essentially what teh random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5101, 0.7002, 0.4711, 0.9075],
        [0.2101, 0.0732, 0.8345, 0.3615],
        [0.0338, 0.8371, 0.3002, 0.9393]])
tensor([[0.0194, 0.6220, 0.0740, 0.7112],
        [0.4834, 0.6604, 0.0109, 0.6978],
        [0.2202, 0.9055, 0.1842, 0.5502]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) # Here is important to both tensors
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest -Use Google Colab for free GPU (options to upgrade as well)
2. Use your own GPU -takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options ..., see this post for what option to get: https://timdettmers.com/category/deep-learning/
3. Use cloud computing -GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them


For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/

In [ ]:
! nvidia-smi

Thu Mar 19 13:19:36 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

### Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
!nvidia-smi

Thu Mar 19 13:25:30 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   65C    P0             28W /   70W |     107MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Exercises & Extra-Curriculum